#!/usr/bin/env python3
"""
HIVE TOOL: report_generator
Generate HTML reports from scan results
"""

import sys
import json
from pathlib import Path
from datetime import datetime

class ReportGenerator:
    """Generate penetration testing reports"""
    
    HTML_TEMPLATE = '''
<!DOCTYPE html>
<html>
<head>
    <title>HIVE Security Assessment Report</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; background: #1a1a2e; color: #eee; }}
        h1 {{ color: #e94560; border-bottom: 3px solid #e94560; padding-bottom: 10px; }}
        h2 {{ color: #0f3460; margin-top: 30px; }}
        .critical {{ color: #ff6b6b; font-weight: bold; }}
        .warning {{ color: #feca57; font-weight: bold; }}
        .info {{ color: #48dbfb; }}
        .section {{ background: #16213e; padding: 20px; margin: 20px 0; border-radius: 8px; }}
        table {{ width: 100%; border-collapse: collapse; margin: 15px 0; }}
        th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #0f3460; }}
        th {{ background: #0f3460; color: white; }}
        tr:hover {{ background: #1a1a2e; }}
        .timestamp {{ color: #888; font-size: 0.9em; }}
    </style>
</head>
<body>
    <h1>🐝 HIVE Security Assessment Report</h1>
    <p class="timestamp">Generated: {timestamp}</p>
    <p><strong>Target:</strong> {target}</p>
    <p><strong>Scope:</strong> {scope}</p>
    
    <div class="section">
        <h2>📊 Executive Summary</h2>
        {summary}
    </div>
    
    <div class="section">
        <h2>🔍 Findings</h2>
        {findings}
    </div>
    
    <div class="section">
        <h2>📋 Recommendations</h2>
        {recommendations}
    </div>
    
    <div class="section">
        <h2>📈 Risk Assessment</h2>
        {risk_matrix}
    </div>
    
    <hr>
    <p class="timestamp">Report generated by HIVE Hacker Edition</p>
    <p class="timestamp">This report is confidential and intended for authorized personnel only.</p>
</body>
</html>
'''
    
    def __init__(self, target, scope=""):
        self.target = target
        self.scope = scope
        self.findings = []
        
    def add_finding(self, title, severity, description, remediation):
        """Add a finding to the report"""
        self.findings.append({
            'title': title,
            'severity': severity,
            'description': description,
            'remediation': remediation
        })
    
    def generate_summary(self):
        """Generate executive summary"""
        critical = len([f for f in self.findings if f['severity'] == 'Critical'])
        high = len([f for f in self.findings if f['severity'] == 'High'])
        medium = len([f for f in self.findings if f['severity'] == 'Medium'])
        low = len([f for f in self.findings if f['severity'] == 'Low'])
        
        return f"""
        <p>This security assessment identified <strong>{len(self.findings)} vulnerabilities</strong> across the target systems.</p>
        <ul>
            <li class="critical">Critical: {critical}</li>
            <li class="warning">High: {high}</li>
            <li class="warning">Medium: {medium}</li>
            <li class="info">Low: {low}</li>
        </ul>
        """
    
    def generate_findings_table(self):
        """Generate findings table"""
        if not self.findings:
            return "<p>No findings reported.</p>"
        
        rows = ""
        for finding in self.findings:
            severity_class = finding['severity'].lower()
            rows += f"""
            <tr>
                <td>{finding['title']}</td>
                <td class="{severity_class}">{finding['severity']}</td>
                <td>{finding['description'][:100]}...</td>
            </tr>
            """
        
        return f"""
        <table>
            <tr>
                <th>Finding</th>
                <th>Severity</th>
                <th>Description</th>
            </tr>
            {rows}
        </table>
        """
    
    def generate_recommendations(self):
        """Generate recommendations"""
        if not self.findings:
            return "<p>No recommendations necessary.</p>"
        
        html = "<ol>"
        for finding in self.findings:
            html += f"<li><strong>{finding['title']}</strong>: {finding['remediation']}</li>"
        html += "</ol>"
        return html
    
    def generate_risk_matrix(self):
        """Generate risk matrix"""
        return """
        <table>
            <tr>
                <th>Risk Level</th>
                <th>Description</th>
                <th>Action Required</th>
            </tr>
            <tr>
                <td class="critical">Critical</td>
                <td>Immediate exploitation possible</td>
                <td>Fix within 24 hours</td>
            </tr>
            <tr>
                <td class="warning">High</td>
                <td>Easy to exploit</td>
                <td>Fix within 7 days</td>
            </tr>
            <tr>
                <td class="warning">Medium</td>
                <td>Moderate complexity</td>
                <td>Fix within 30 days</td>
            </tr>
            <tr>
                <td class="info">Low</td>
                <td>Low impact</td>
                <td>Fix in next release</td>
            </tr>
        </table>
        """
    
    def save(self, output_path):
        """Save report to file"""
        html = self.HTML_TEMPLATE.format(
            timestamp=datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            target=self.target,
            scope=self.scope,
            summary=self.generate_summary(),
            findings=self.generate_findings_table(),
            recommendations=self.generate_recommendations(),
            risk_matrix=self.generate_risk_matrix()
        )
        
        Path(output_path).write_text(html)
        return output_path

def main():
    print("""
╔══════════════════════════════════════════╗
║  📄 HIVE Report Generator                 ║
║  Professional penetration test reports   ║
╚══════════════════════════════════════════╝
    """)
    
    target = input("Target: ").strip()
    scope = input("Scope: ").strip()
    output = input("Output file (default: report.html): ").strip() or "report.html"
    
    report = ReportGenerator(target, scope)
    
    # Interactive finding entry
    print("\n📝 Enter findings (leave title empty to finish):")
    while True:
        title = input("\nFinding title: ").strip()
        if not title:
            break
        
        severity = input("Severity (Critical/High/Medium/Low): ").strip()
        description = input("Description: ").strip()
        remediation = input("Remediation: ").strip()
        
        report.add_finding(title, severity, description, remediation)
    
    # Generate report
    path = report.save(output)
    print(f"\n✓ Report saved: {path}")

if __name__ == "__main__":
    main()
